### ISSUE TITLE
NSNumber to BOOL on 64 bit

### ISSUE THREAD

**Issue by ghost** [RestKit/RKValueTransformers#12]
There seems to be a bug converting NSNumber to BOOL on 64 bit iOS devices. This is a StackOverflow link to the issue that includes a great work around by sergio.

http://stackoverflow.com/questions/22175313/restkit-does-not-map-bool-in-64-bit-simulator/22349468?noredirect=1#22349468

**Comment by ABorshche** [comment]
@segiddins , here is a failing test.
```objective-c
- (void)testNumberToArm64BOOLValueTransformationForTrueValue {
    RKCompoundValueTransformer *valueTransformer = [RKValueTransformer defaultValueTransformer];
    id value = nil;
    NSError *error = nil;
    BOOL success = [valueTransformer transformValue:@1 toValue:&value ofClass:NSClassFromString(@"__NSCFBoolean") error:&error];
    expect(success).to.beTruthy();
    expect(value).to.equal(@(YES));
}
```
and **__NSCFBoolean** comes from [RKObjectUtilities.m#L99-L102](https://github.com/RestKit/RestKit/blob/development/Code/ObjectMapping/RKObjectUtilities.m#L99-L102)

**Comment by segiddins** [comment]
Take a look at https://github.com/RestKit/RKValueTransformers/pull/20, which should address the issue. Thanks so much @ABorshche for the failing test!

**Comment by iwasrobbed** [comment]
Nice work @ABorshche and @segiddins. Thanks for following up on this
