### ISSUE TITLE
bug in iso8601TimestampToDateValueTransformer – cannot parse microseconds

### ISSUE THREAD

**Issue by hexrain** [RestKit/RKValueTransformers#26]
There's a bug in iso8601TimestampToDateValueTransformer.

Regex is allowing up to 6 digits in milliseconds section, see below

```
static const char * REGEX_ISO8601_TIMESTAMP =
                "\\A(\\d{4})-(\\d{2})-(\\d{2})[T\\s](\\d{2}):(\\d{2}):(\\d{2})" // Mandatory - YYYY-MM-DD(T|\s)hh:mm:ss
                "(?:"
                "[.](\\d{1,6})"                                   // Optional - .nnnnnn
                ")?"
                "(?:"
                "([+-])(\\d{2}):?(\\d{2})|Z"                       // Optional -[+-]hh:?mm or Z
                ")?\\z";
```
But that means that the time precision depends on the number of characters supplied.

But in the following lines I see the division by 1000 that suggests that `iso8601TimestampToDateValueTransformer` only supports milliseconds.

```
inputValue = [NSString stringWithString:newInputString];
milliseconds = [millisecondsString doubleValue]/1000.f;
```

I suggest changing it to
`milliseconds = [millisecondsString doubleValue] / pow(10, millisecondsString.length);`

**Comment by segiddins** [comment]
Closed by https://github.com/RestKit/RKValueTransformers/issues/27.
